name: benchmarks

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmarks
    defaults:
        run:
          # needed for conda to be able to work
          shell: bash -l {0}
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.8"
    - uses: actions/checkout@v1
    - name: Install
      run: pip install .
    - name: Install pynbwb and fsspec
      run: pip install pynwb fsspec aiohttp requests
    - name: Install the conda version of h5py which has ros3 support
      run: pip uninstall -y h5py && conda install -y -c conda-forge "h5py>=3.2"
    - name: Run benchmarks
      run: python benchmarks/benchmarks.py